EaseFlight.Web/Areas/Admin/Controllers/AirportController.cs
using EaseFlight.BLL.Interfaces;
using EaseFlight.Models.EntityModels;
using System.Web.Mvc;

namespace EaseFlight.Web.Areas.Admin.Controllers
{
    public class AirportController : BaseController
    {
        #region Properties
        private IAirportService AirportService { get; set; }
        private ICountryService CountryService { get; set; }
        #endregion

        #region Constructor
        public AirportController(IAirportService airportService, ICountryService countryService)
        {
            this.AirportService = airportService;
            this.CountryService = countryService;
        }
        #endregion

        #region Action
        [HttpGet]
        public ActionResult Index()
        {
            ViewData["airport"] = this.AirportService.FindAll();
            ViewData["countrys"] = this.CountryService.FindAll();
            return View();
        }

        [HttpPost]
        public ActionResult AddNewAirport(FormCollection collection)
        {
            var airport = new AirportModel
            {
                Name = collection.Get("name"),
                City = collection.Get("city"),
                CountryID = int.Parse(collection.Get("countryid"))
            };

            this.AirportService.Insert(airport);
            TempData["msg"] = "success-Country add successfully";

            return RedirectToAction("Index");
        }

        [HttpPost]
        public ActionResult UpdateAirport(FormCollection collection)
        {
            var currentAirpot = this.AirportService.Find(int.Parse(collection.Get("airportid")));

            currentAirpot.Name = collection.Get("name");
            currentAirpot.City = collection.Get("city");
            currentAirpot.CountryID = int.Parse(collection.Get("countryid"));

            this.AirportService.Update(currentAirpot);
            TempData["msg"] = "success-Country update successfully";

            return RedirectToAction("Index");
        }

        [HttpPost]
        public JsonResult DeleteAirport(int airportid)
        {
            this.AirportService.Delete(airportid);
            TempData["msg"] = "success-Country delete successfully";

            return new JsonResult { ContentType = "text" };
        }
        #endregion
    }
}

EaseFlight.Web/Areas/Admin/Controllers/TicketController.cs
using EaseFlight.BLL.Interfaces;
using EaseFlight.Common.Constants;
using EaseFlight.Models.CustomModel;
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Web.Mvc;

namespace EaseFlight.Web.Areas.Admin.Controllers
{
    public class TicketController : BaseController
    {
        #region Properties
        private ITicketService TicketService { get; set; }
        private IFlightService FlightService { get; set; }
        private IAirportService AirportService { get; set; }
        private ISeatMapService SeatMapService { get; set; }
        private ITicketFlightService TicketFlightService { get; set; }
        private IPassengerTicketService PassengerTicketService { get; set; }
        #endregion

        #region Constructor
        public TicketController(ITicketService ticketService, IFlightService flightService, IPassengerTicketService passengerTicketService,
            IAirportService airportService, ISeatMapService seatMapService, ITicketFlightService ticketFlightService)
        {
            this.TicketService = ticketService;
            this.FlightService = flightService;
            this.AirportService = airportService;
            this.SeatMapService = seatMapService;
            this.TicketFlightService = ticketFlightService;
            this.PassengerTicketService = passengerTicketService;
        }
        #endregion

        #region Actions
        public ActionResult Index()
        {
            var tickets = this.TicketService.FindAll();

            var model = new List<TicketHistoryModel>();

            foreach (var ticket in tickets)
            {
                var departFlight = this.FlightService.FindByTicket(ticket.ID).ToList();
                var returnFlight = this.FlightService.FindByTicket(ticket.ID, true).ToList();
                var passengers = this.PassengerTicketService.FindByTicket(ticket.ID).ToList();
                var firstTicketFlight = this.TicketFlightService.FindByTicket(ticket.ID).First();

                model.Add(new TicketHistoryModel
                {
                    Ticket = ticket,
                    From = this.AirportService.Find(departFlight.First().Departure.ID),
                    To = this.AirportService.Find(departFlight.Last().Arrival.ID),
                    SeatClass = this.SeatMapService.FindBySeatCode(firstTicketFlight.SeatCode.Split(',').First(), firstTicketFlight.Flight.PlaneID.Value),
                    DepartFlight = departFlight,
                    ReturnFlight = returnFlight,
                    Passengers = passengers,
                    TicketFlightList = this.TicketFlightService.FindByTicket(ticket.ID).ToList()
                });
            }

            ViewData["tickets"] = model;

            return View();
        }

        [HttpPost]
        public JsonResult UpdatePassenger(FormCollection collection)
        {
            var result = new JsonResult { ContentType = "text" };
            var currentPassenger = this.PassengerTicketService.Find(int.Parse(collection.Get("passengerId")));

            currentPassenger.FirstName = collection.Get("firstname");
            currentPassenger.LastName = collection.Get("lastname");
            currentPassenger.Gender = collection.Get("title").Equals("1") ? true : false;
            currentPassenger.Birthday = DateTime.ParseExact(collection.Get("birthday"), "dd/MM/yyyy", CultureInfo.InvariantCulture);
            currentPassenger.IDCardOrPassport = collection.Get("passport");
            currentPassenger.PlaceIssue = string.Concat(collection.Get("nationality"), string.IsNullOrEmpty(collection.Get("city")) ? "" : ", " + collection.Get("city"));

            if (string.IsNullOrEmpty(collection.Get("expiry")))
                currentPassenger.DateIssueOrExpiry = null;
            else currentPassenger.DateIssueOrExpiry = DateTime.ParseExact(collection.Get("expiry"), "dd/MM/yyyy", CultureInfo.InvariantCulture);

            this.PassengerTicketService.Update(currentPassenger);

            return result;
        }

        [HttpPost]
        public JsonResult CancelTicket(string ticketId)
        {
            var result = new JsonResult { ContentType = "text" };
            var currentTicket = this.TicketService.Find(int.Parse(ticketId));

            if (currentTicket == null || currentTicket.Status.Equals(Constant.CONST_DB_TICKET_STATUS_CANCEL))
            {
                result.Data = new { type = "error" };
                return result;
            }

            currentTicket.Status = Constant.CONST_DB_TICKET_STATUS_CANCEL;
            result.Data = new { type = "success" };
            this.TicketService.Update(currentTicket);

            return result;
        }

        [HttpPost]
        public JsonResult DeleteTicket(string ticketId)
        {
            var result = new JsonResult { ContentType = "text" };
            var currentTicket = this.TicketService.Find(int.Parse(ticketId));

            if(currentTicket != null && currentTicket.Status.Equals(Constant.CONST_DB_TICKET_STATUS_CANCEL))
            {

                result.Data = new { type = "success" };
            }

            return result;
        }
        #endregion
    }
}

EaseFlight.Web/Controllers/FlightController.cs
using EaseFlight.BLL.Interfaces;
using EaseFlight.Common.Constants;
using EaseFlight.Models.CustomModel;
using EaseFlight.Models.EntityModels;
using EaseFlight.Web.WebUtilities;
using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Web.Mvc;

namespace EaseFlight.Web.Controllers
{
    public class FlightController : Controller
    {
        #region Properties
        private IAirportService AirportService { get; set; }
        private ISeatClassService SeatClassService { get; set; }
        private IFlightService FlightService { get; set; }
        private ICountryService CountryService { get; set; }
        private IPassengerTypeService PassengerTypeService { get; set; }
        private ISeatMapService SeatMapService { get; set; }
        #endregion

        #region Constructors
        public FlightController(IAirportService airportService, ISeatClassService seatClassService,
            IFlightService flightService, ICountryService countryService, IPassengerTypeService passengerTypeService,
            ISeatMapService seatMapService)
        {
            this.AirportService = airportService;
            this.SeatClassService = seatClassService;
            this.FlightService = flightService;
            this.CountryService = countryService;
            this.PassengerTypeService = passengerTypeService;
            this.SeatMapService = seatMapService;
        }
        #endregion

        #region Actions
        [HttpGet]
        public ActionResult Find()
        {
            var airports = this.AirportService.FindAll();
            var regions = this.CountryService.FindAll().Select(country => country.Region).Distinct();
            var passengers = this.PassengerTypeService.FindAll();
            var airportRegion = new List<AirportRegionModel>
            {
                new AirportRegionModel
                {
                    Region = Constant.CONST_DB_NAME_VIETNAM,
                    Airports = airports.Where(airport => airport.Country.Name.Equals(Constant.CONST_DB_NAME_VIETNAM))
                        .OrderBy(airport => airport.Name)
                }
            };

            foreach (var region in regions)
            {
                var airportList = airports.Where(airport => airport.Country.Region.Equals(region)
                && !airport.Country.Name.Equals(Constant.CONST_DB_NAME_VIETNAM));

                if (airportList.Count() != 0)
                    airportRegion.Add(new AirportRegionModel
                    {
                        Region = region,
                        Airports = airportList
                    });
            }

            ViewData["airports"] = airportRegion;
            ViewData["passengers"] = passengers;
            ViewData["seatClassList"] = this.SeatClassService.FindAll();
            SessionUtility.RemoveBookingSession();

            return View();
        }

        [HttpPost]
        public JsonResult GetSearchValue(FormCollection collection)
        {
            var result = new JsonResult { ContentType = "text" };

            try
            {
                var departure = this.AirportService.Find(int.Parse(collection.Get("departure")));
                var arrival = this.AirportService.Find(int.Parse(collection.Get("arrival")));
                var departureDate = DateTime.ParseExact(collection.Get("date"), "dd/MM/yyyy", CultureInfo.InvariantCulture);
                var returnDate = string.IsNullOrEmpty(collection.Get("return")) ? new DateTime()
                    : DateTime.ParseExact(collection.Get("return"), "dd/MM/yyyy", CultureInfo.InvariantCulture);
                var seatClass = this.SeatClassService.Find(int.Parse(collection.Get("seat")));
                var adultPassenger = int.Parse(collection.Get("adult"));
                var childPassenger = int.Parse(collection.Get("child"));
                var infantPassenger = int.Parse(collection.Get("infant"));
                var isRoundTrip = bool.Parse(collection.Get("roundtrip"));

                result.Data = new 
                {
                    departure = departure.ID,
                    arrival = arrival.ID,
                    date = departureDate.ToString("yyyy-MM-dd"),
                    returnDate = returnDate.ToString("yyyy-MM-dd"),
                    seat = seatClass.Name.Replace(" ",""),
                    adult = adultPassenger,
                    child = childPassenger,
                    infant = infantPassenger,
                    roundTrip = isRoundTrip
                };
            }
            catch
            {

            }

            return result;
        }

        [HttpPost]
        public JsonResult Find(FormCollection collection)
        {
            this.FlightService.UpdateFlightDone();
            var result = new JsonResult { ContentType = "text" };

            try
            {
                var departure = this.AirportService.Find(int.Parse(collection.Get("departure")));
                var arrival = this.AirportService.Find(int.Parse(collection.Get("arrival")));
                var departureDate = DateTime.ParseExact(collection.Get("date"), "dd/MM/yyyy", CultureInfo.InvariantCulture);
                var returnDate = string.IsNullOrEmpty(collection.Get("return")) ? new DateTime()
                    : DateTime.ParseExact(collection.Get("return"), "dd/MM/yyyy", CultureInfo.InvariantCulture);
                var seatClass = this.SeatClassService.Find(int.Parse(collection.Get("seat")));
                var adult = int.Parse(collection.Get("adult"));
                var child = int.Parse(collection.Get("child"));
                var infant = int.Parse(collection.Get("infant"));
                var roundTrip = bool.Parse(collection.Get("roundtrip"));
                var pageDepart = int.Parse(collection.Get("pageDepart"));
                var pageReturn = int.Parse(collection.Get("pageReturn"));

                if (departure == null || arrival == null || seatClass == null || (roundTrip && returnDate.Year == 1)
                    || (roundTrip && returnDate.Date < departureDate.Date) || adult < 1 || (adult + child + infant) > 10 || adult < (child + infant))
                    result.Data = new { type = "error" };
                else
                {
                    var searchDepartureList = this.FlightService.FindFlight(departure, arrival, departureDate);
                    var totalSeat = adult + child;
                    var returnData = new List<SearchFlightModel>();
                    var departureData = SearchFlight(searchDepartureList, totalSeat, seatClass).OrderBy(flight => flight.Price);

                    if (roundTrip)
                    {
                        var searchReturnList = this.FlightService.FindFlight(arrival, departure, returnDate);
                        returnData = SearchFlight(searchReturnList, totalSeat, seatClass).OrderBy(flight => flight.Price).ToList();
                    }

                    var model = new ResultFlightModel
                    {
                        DepartureData = departureData.Take(pageDepart).ToList(),
                        ReturnData = returnData.Take(pageReturn).ToList(),
                        From = departure,
                        To = arrival,
                        SeatClass = seatClass,
                        PageSize = new List<int> { departureData.Count(), returnData.Count()}
                    };

                    result.Data = new { type = "success", result = RenderViewToString(this.ControllerContext , "_FlightResultPartial", model) };
                }
            }
            catch
            {
                result.Data = new { type = "error" };
            }

            return result;
        }

        [HttpGet]
        public ActionResult Booking()
        {
            if (SessionUtility.GetBookingSession() == null || !SessionUtility.IsSessionAlive())
                return RedirectToAction("Index", "Home");

            return View();
        }

        [HttpPost]
        public JsonResult Booking(FormCollection collection)
        {
            var result = new JsonResult { ContentType = "text" };
            var departure = this.AirportService.Find(int.Parse(collection.Get("departure")));
            var arrival = this.AirportService.Find(int.Parse(collection.Get("arrival")));
            var seatClass = this.SeatClassService.Find(int.Parse(collection.Get("seat")));
            var adult = int.Parse(collection.Get("adult"));
            var child = int.Parse(collection.Get("child"));
            var infant = int.Parse(collection.Get("infant"));
            var price = double.Parse(collection.Get("price"));
            var roundTrip = bool.Parse(collection.Get("roundtrip"));
            var flightDepart = collection.Get("flightDepart").Split('.').ToList();
            var flightReturn = collection.Get("flightReturn").Split('.').ToList();
            var departList = new List<FlightModel>();
            var returnList = new List<FlightModel>();
            var passengerType = this.PassengerTypeService.FindAll().ToList();

            flightDepart.ForEach(id => departList.Add(this.FlightService.Find(int.Parse(id))));

            if(roundTrip)
                flightReturn.ForEach(id => returnList.Add(this.FlightService.Find(int.Parse(id))));

            var booking = new BookingModel
            {
                DepartFlight = departList,
                ReturnFlight = returnList,
                Departure = departure,
                Arrival = arrival,
                SeatClass = seatClass,
                PassengerType = passengerType,
                Adult = adult,
                Child = child,
                Infant = infant,
                Price = price
            };

            SessionUtility.SetBookingSession(booking);

            return result;
        }
        #endregion

        #region Private Funtions

EaseFlight.Web/Areas/Admin/Views/Shared/_Layout.cshtml
@using EaseFlight.Web.WebUtilities;
@{
    var loggedUser = SessionUtility.GetLoggedUser();
    var fullName = (loggedUser.Gender != null ? loggedUser.Gender.Value ? "Ms/Mrs. " : "Mr. " : "") + loggedUser.FirstName + " " + loggedUser.LastName;
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <meta http-equiv="Content-Security-Policy" content="upgrade-insecure-requests">
    <title>EaseFlight Admin - @ViewBag.Title</title>
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">
    @Styles.Render("~/Content/adminbasecss")
    @Styles.Render("~/Content/adminlogin")
    @Scripts.Render("~/bundles/adminbasejs")
    @Scripts.Render("~/bundles/admincontextmenu")
</head>

<body class="hold-transition sidebar-mini">
    <div class="wrapper">
        <nav class="main-header navbar navbar-expand navbar-white navbar-light">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" data-widget="pushmenu" href="#"><i class="fas fa-bars"></i></a>
                </li>
            </ul>
            <ul class="navbar-nav ml-auto">
                <li class="nav-item dropdown">
                    <a class="nav-link nav-avt" data-toggle="dropdown" href="#">
                        <img src="@(string.IsNullOrEmpty(loggedUser.Photo)?"/Content/images/avatar/user.png":loggedUser.Photo)" width="25" height="25" />
                    </a>
                    <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
                        <span class="dropdown-item dropdown-header">@fullName ✿ @loggedUser.AccountType.Name</span>
                        <div class="dropdown-divider"></div>
                        <a href="@Url.Action("MyProfile","Account", new { Area = "" })" class="dropdown-item">
                            <i class="fas fa-user mr-2"></i> My Profile
                        </a>
                        <div class="dropdown-divider"></div>
                        <a href="@Url.Action("Logout","Account", new { Area = "Admin"})" class="dropdown-item">
                            <i class="fas fa-angle-right mr-2"></i> Sign Out
                        </a>
                    </div>
                </li>
            </ul>
        </nav>
        <aside class="main-sidebar sidebar-dark-primary elevation-4">
            <a href="/Admin" class="brand-link">
                <img src="~/Content/images/logo.png" alt="EaseFlight Logo" class="brand-image img-circle"
                     style="opacity: .8">
                <span class="brand-text font-weight-light">Ease Flight</span>
            </a>
            <div class="sidebar">
                <div class="user-panel mt-3 pb-3 mb-3 d-flex">
                    <div class="image">
                        <img src="@(string.IsNullOrEmpty(loggedUser.Photo)?"/Content/images/avatar/user.png":loggedUser.Photo)" class="img-circle elevation-2" alt="User Image">
                    </div>
                    <div class="info">
                        <a href="#" class="d-block">@fullName</a>
                    </div>
                </div>
                <nav class="mt-2">
                    <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
                        <li class="nav-item">
                            <a href="/Admin" class="nav-link dashboard-menu">
                                <i class="nav-icon fas fa-tachometer-alt"></i>
                                <p>Dashboard</p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="@Url.Action("Index","Flight")" class="nav-link flight-menu">
                                <i class="nav-icon fas fa-plane-departure"></i>
                                <p>Flight Management</p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="@Url.Action("Index","Ticket")" class="nav-link ticket-menu">
                                <i class="nav-icon fas fa-credit-card"></i>
                                <p>Ticket Management</p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="@Url.Action("Index","Airport")" class="nav-link airport-menu">
                                <i class="nav-icon fas fa-route"></i>
                                <p>Airport Management</p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="@Url.Action("Index","Plane")" class="nav-link plane-menu">
                                <i class="nav-icon fas fa-plane"></i>
                                <p>Aircraft Management</p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="@Url.Action("Index","Country")" class="nav-link country-menu">
                                <i class="nav-icon fas fa-globe-asia"></i>
                                <p>Country Management</p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="@Url.Action("Index","Account")" class="nav-link account-menu">
                                <i class="nav-icon fas fa-users"></i>
                                <p>Account Management</p>
                            </a>
                        </li>
                    </ul>
                </nav>
            </div>
        </aside>
        <div class="content-wrapper">
            <div class="content-header">
                <div class="container-fluid">
                    <div class="row mb-2">
                        <div class="col-sm-6">
                            <h1 class="m-0 text-dark">@ViewBag.Title Management</h1>
                        </div>
                        <div class="col-sm-6">
                            <ol class="breadcrumb float-sm-right">
                                <li class="breadcrumb-item"><a href="#">Home</a></li>
                                <li class="breadcrumb-item active">@ViewBag.Title</li>
                            </ol>
                        </div>
                    </div>
                </div>
            </div>
            <div class="content">
                <div class="container-fluid">
                    @RenderBody()
                </div>
            </div>
        </div>
        <aside class="control-sidebar control-sidebar-dark">
        </aside>
        <footer class="main-footer">
            <strong>Copyright &copy; @DateTime.Now.Year <a href="/">EaseFllight</a>.</strong>
            All rights reserved.
        </footer>
    </div>
</body>
</html>